// Generated from packages/policy-api/src/spec.ts. Do not edit.

/** Built-in policies shipped with the application, by name. */
export const BUILT_IN_POLICIES = {
  "balance-stock":
    "-- Balance stock: how Surviving Mars: Relaunched trains appear to decide what to\n-- carry, based on observed behaviour and not yet verified against the game.\n--\n-- At every stop, each resource the station stores is moved towards the average\n-- stock of that resource across all stations on the line that store it. Nothing\n-- else is considered: not how fast stations consume or produce, not what other\n-- trains carry, and not which station needs the resource most.\n--\n-- The ops.balance documentation page shows the same rule written in plain Lua.\n\nreturn ops.policy { target = ops.balance {} }\n",
  "supply-to-demand":
    '-- Supply to demand: an example policy built from ops blocks.\n--\n-- Stations are given roles by hand for the starter scenarios. Trains empty the\n-- stations that produce a resource, fill the stations that need it, and pass\n-- relays by. Lookahead keeps cargo for stations further along and reserves it,\n-- so a second train does not answer a shortage that is already covered. When a\n-- train cannot carry everything, higher priority resources go first.\n\nreturn ops.policy {\n  classify = ops.roles.manual {\n    -- Mining outposts and the farm produce; domes and factories consume.\n    Mine = { Metals = "supply", Food = "demand" },\n    Farm = { Food = "supply", Metals = "demand" },\n    Plant = { Polymers = "supply", Metals = "demand" },\n    Factory = "demand",\n    Dome = "demand",\n    Junction = "relay",\n    Depot = "relay",\n  },\n  target = {\n    supply = ops.drain {},\n    demand = ops.fill {},\n    relay = ops.pass_through {},\n  },\n  plan = ops.lookahead {},\n  allocate = ops.priority {},\n}\n',
} as const;
