// Generated from packages/scenario-kit. Do not edit.

/** Starter scenarios as Mars pack scripts, by scenario id. */
export const STARTER_SCRIPTS: Record<string, string> = {
  "mixed-line":
    '-- Mixed line: ping-pong and missing priorities.\n\nreturn mars.line {\n  id = "mixed-line",\n  title = "Mixed line",\n  description = "Five stations trade food, metals and polymers of different "\n    .. "importance. Balancing carries goods back and forth between stations "\n    .. "that neither produce nor need them, and treats food the same as "\n    .. "metals.",\n  docs = "failure-modes/ping-pong",\n  duration = sols(10),\n  resources = { "Metals", "Polymers", "Food" },\n  stations = {\n    mars.small_station {\n      id = "Farm",\n      capacity = { Food = 60 },\n      stock = { Food = 30, Metals = 10 },\n      buildings = {\n        mars.farm { rate = 60 },\n        mars.consumer { resource = "Metals", rate = 4 },\n      },\n    },\n    mars.small_station {\n      id = "Mine",\n      capacity = { Metals = 60 },\n      stock = { Metals = 30, Food = 10 },\n      buildings = {\n        mars.extractor { resource = "Metals", rate = 40 },\n        mars.consumer { resource = "Food", rate = 8 },\n      },\n    },\n    mars.small_station {\n      id = "Depot",\n      resources = { "Metals", "Polymers", "Food" },\n    },\n    mars.small_station {\n      id = "Plant",\n      stock = { Polymers = 15, Metals = 10 },\n      buildings = {\n        mars.producer { resource = "Polymers", rate = 24 },\n        mars.consumer { resource = "Metals", rate = 12, variability = 25 },\n      },\n    },\n    mars.small_station {\n      id = "Dome",\n      capacity = { Food = 60 },\n      stock = { Food = 30, Polymers = 15, Metals = 15 },\n      buildings = {\n        mars.dome {\n          consumes = {\n            { "Food", 45, variability = 20 },\n            { "Polymers", 16 },\n            {\n              "Metals",\n              16,\n              variability = bursts { on_ppm = 1500, off_ppm = 1500 },\n            },\n          },\n        },\n      },\n    },\n  },\n  distances = { 18000, 24000, 18000, 30000 },\n  trains = {\n    mars.train { id = "T1", start = "Farm", speed = 6 },\n    mars.train { id = "T2", start = "Dome", direction = "backward", speed = 6 },\n  },\n}\n',
  relay:
    '-- Relay station: dead stock at a junction.\n\nreturn mars.line {\n  id = "relay",\n  title = "Relay station",\n  description = "A junction station with no producers or consumers sits "\n    .. "between a mine and a dome. Balancing fills it to the line average, "\n    .. "tying up stock the dome needs.",\n  docs = "book/flows#case-study-dead-stock",\n  duration = sols(10),\n  stations = {\n    mars.small_station {\n      id = "Mine",\n      stock = { Metals = 15 },\n      buildings = { mars.extractor { resource = "Metals", rate = 45 } },\n    },\n    mars.small_station { id = "Junction", resources = { "Metals" } },\n    mars.small_station {\n      id = "Dome",\n      stock = { Metals = 15 },\n      buildings = {\n        mars.consumer { resource = "Metals", rate = 34, variability = 20 },\n      },\n    },\n  },\n  distances = 36000,\n  trains = { mars.train { id = "T1", start = "Mine" } },\n}\n',
  "storm-shock":
    '-- Storm shock: a storm, then a maintenance surge.\n\nreturn mars.line {\n  id = "storm-shock",\n  title = "Storm shock",\n  description = "A dust storm stops the mine\'s extractors for a sol, and the "\n    .. "damage it leaves behind sends metal demand at the dome up for a sol "\n    .. "and a half. Balancing runs the dome close to empty in normal "\n    .. "operation, so it has no buffer for either shock and recovers slowly.",\n  docs = "book/safety-stock#case-study-storm-shock",\n  duration = sols(10),\n  stations = {\n    mars.small_station {\n      id = "Mine",\n      stock = { Metals = 15 },\n      buildings = { mars.extractor { resource = "Metals", rate = 40 } },\n    },\n    mars.small_station {\n      id = "Dome",\n      stock = { Metals = 15 },\n      buildings = {\n        mars.consumer { resource = "Metals", rate = 24, variability = 20 },\n      },\n    },\n  },\n  distances = 72000,\n  trains = { mars.train { id = "T1", start = "Mine" } },\n  events = {\n    mars.dust_storm {\n      start = sols(3),\n      duration = sols(1),\n      surge = {\n        station = "Dome",\n        resource = "Metals",\n        multiplier = 2.5,\n        after = sols(0.5),\n        duration = sols(1.5),\n      },\n    },\n  },\n}\n',
  "two-station":
    '-- Two stations: the half capacity limit.\n\nreturn mars.line {\n  id = "two-station",\n  title = "Two stations",\n  description = "A mining outpost supplies a dome over a long line with one "\n    .. "train. Balancing moves at most half the stock difference per visit, "\n    .. "so the dome runs short while the mine\'s station fills and its "\n    .. "extractors stall, even though one train could carry enough.",\n  docs = "book/modelling#case-study-half-capacity",\n  duration = sols(10),\n  stations = {\n    mars.small_station {\n      id = "Mine",\n      stock = { Metals = 15 },\n      buildings = { mars.extractor { resource = "Metals", rate = 45 } },\n    },\n    mars.small_station {\n      id = "Dome",\n      stock = { Metals = 15 },\n      buildings = {\n        mars.consumer { resource = "Metals", rate = 36, variability = 20 },\n      },\n    },\n  },\n  distances = 72000,\n  trains = { mars.train { id = "T1", start = "Mine" } },\n}\n',
  "two-trains":
    '-- Two trains: double dispatch.\n\nreturn mars.line {\n  id = "two-trains",\n  title = "Two trains",\n  description = "Two trains share a line from a mine to a factory and a dome. "\n    .. "Without knowing what the other train is carrying, both respond to the "\n    .. "same shortage, oversupplying one station while the other waits.",\n  docs = "book/base-stock#case-study-double-dispatch",\n  duration = sols(10),\n  stations = {\n    mars.large_station {\n      id = "Mine",\n      stock = { Metals = 30 },\n      buildings = { mars.extractor { resource = "Metals", rate = 80 } },\n    },\n    mars.small_station {\n      id = "Factory",\n      stock = { Metals = 15 },\n      buildings = {\n        mars.consumer {\n          resource = "Metals",\n          rate = 40,\n          variability = bursts { on_ppm = 2000, off_ppm = 1000 },\n        },\n      },\n    },\n    mars.small_station {\n      id = "Dome",\n      stock = { Metals = 15 },\n      buildings = {\n        mars.consumer { resource = "Metals", rate = 42, variability = 30 },\n      },\n    },\n  },\n  distances = { 30000, 42000 },\n  trains = {\n    mars.train { id = "T1", start = "Mine" },\n    mars.train { id = "T2", start = "Dome", direction = "backward" },\n  },\n}\n',
};
